# Area of Triangle
base = float(input("Enter base of triangle: "))
height = float(input("Enter height of triangle: "))

area_triangle = 0.5 * base * height
print("Area of Triangle:", area_triangle)

# Area of Rectangle
length = float(input("Enter length of rectangle: "))
width = float(input("Enter width of rectangle: "))

area_rectangle = length * width
print("Area of Rectangle:", area_rectangle)